### PR TITLE
Feature/mitigation effects integration

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR integrates the mitigation effects backend and displays it in the bubble chart:

- Parse data from the backend
- Theme and GHG Emissions Reduction selection
- Make available GHG... depend on Theme
- Update API docs
- All URL params in snake case

Note: All the not estimated, not applicable, null or 0 values are not displayed. Also, there are some values that have to be changed in the data (6-3 = 6*10**-3)

image

### CODE REVIEW

**Comment by aabdaab** [comment]
Not sure what you think about it but maybe it is worth to always have a default data chosen? So on initial render and changing selectors it's not blank:
image

**Comment by Bluesmile82** [comment]
Good request! Ready again

**Comment by aabdaab** [comment]
Thanks for the change!
I have a weird behaviour when selecting the last theme in the dropdown `Expanded Public Works...`. When I select it, there is no Data Available (👍 ) but the selector doesn't change. When then I change it to `Energy Efficiency` it says again no Data Available which is wrong

**Comment by Bluesmile82** [comment]
Ready again! Thanks for the catch

**Pull request merged**
