### PR TITLE
Fix/ghg emissions selectors

### PR DESCRIPTION
**Pull request by Bluesmile82**
This PR:

- Adds gases selector and filters
- Adds subsector selector, splits sectors and subsectors

Notes:
- 'Total GHG' gas is excluded as we already have 'TotalGHG' with data
- Right now we only have gas data in 'TotalGHG'
- Maybe we could improve the multiselect in the case that we have only one item selected showing that item instead of '1 selected'
- I tried to extract nested selector but is still in process in a branch in cw-components

image

### CODE REVIEW

**Comment by Bluesmile82** [comment]
Ready again! I had to extend the colors, fix the legend adding subsectors and fix the columns to a particular color. The colors could be quite similar between them but it's the best I can do.

**Comment by Bluesmile82** [comment]
Fixed! Thanks for the catch

**Comment by simaob** [comment]
There seems to be a bug with the sectors selector. If I deselect a sector I can no longer select it. :(

**Comment by Bluesmile82** [comment]
Thanks! A little bit was missing. Ready again

**Comment by simaob** [comment]
Cool, now it's working =)

**Pull request merged**
