### PR TITLE
Added the importing of the projected emissions scenarios metadata and…

### PR DESCRIPTION
**Pull request by santostiago**
… displayed it in the endpoint's response

### CODE REVIEW

**Comment by simaob** [comment]
The import is not working for me. But I think it might be related to the location of the files. my CW_FILES_PREFIX is pointing to: `climatewatch.org/staging.climatewatch.org/south-africa/`.
This is the new bucket that we will be using on staging. So we need to make sure that the files are all in there! =) Check with Marta, please! =)

**Comment by aabdaab** [comment]
@simaob make sure that you have the new env variables set correctly (AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, S3_BUCKET_NAME=wri-sites)

**Comment by simaob** [comment]
Thanks! =) that made it work 🙇

**Comment by simaob** [comment]
Works well! =)

**Pull request merged**
