### PR TITLE
Add sustainable benefits table

### PR DESCRIPTION
**Pull request by Bluesmile82**
Add table option to the mitigation effects section

- The table is filtered by theme and the All selected option has been added only in the table vizType

image

### CODE REVIEW

**Comment by simaob** [comment]
Hi Álvaro, is this PR relative to this Story: https://www.pivotaltracker.com/story/show/161545911 ?
The task is to add a second "visualisation" on the first tab of the Mitigation Effects page where currently we only have "bubbles". We should add a second option called "Table" where we show the same data that we have on the bubbles.

The second "pill" I believe needs new data to be imported.

**Comment by simaob** [comment]
On the other hand we also need to figure out where is the sustainable development data 😓

**Comment by Bluesmile82** [comment]
Thanks, I was a bit confused with this one. Do we have the Sustainable Benefits data? Is it going to be a table as well?

**Comment by Bluesmile82** [comment]
Ok, ready again! Please check it out

**Pull request merged**
