### PR TITLE
Feature/scenario tooltip

### PR DESCRIPTION
**Pull request by weberjavi**
This PR adds a tooltip definition to projected emissions graph.
[Pivotal task](https://www.pivotaltracker.com/n/projects/2083759/stories/161545875)

To test the implementation head:
http://localhost:3000/ghg-emissions/projected-emissions

kapture 2018-11-06 at 14 15 49

### CODE REVIEW

**Comment by Bluesmile82** [comment]
There is a problem when deleting an element from the legend. Suddenly all are gone and you can't put them back. Might be a problem with the selected elements filter

**Comment by Bluesmile82** [comment]
Also, GHG Inventory doesn't have a tooltip but it might be because we don't have data yet. Maybe we should remove it until the data source is clear

**Comment by weberjavi** [comment]
@Bluesmile82 please check the changes ☝️ 
About the `GHG inventory` data not sure what's the best approach. Any thoughts about that @simaob ?

**Comment by simaob** [comment]
It's because we don't have the data yet. Let's leave it in a way that when the data is populated this will show automatically!

**Comment by Bluesmile82** [comment]
Working fine now! Thanks! Feel free to merge

**Pull request merged**
