### PR TITLE
ActiveAdmin

### PR DESCRIPTION
**Pull request by agnessa**
Admin panel for SA. Added following the same approach as in ClimateWatch, meaning also with a shared database; I followed the pattern with a shared database to have it done in same way in all platforms, regardless of deployment considerations; let me know if that's overdoing it in case of SA.

### CODE REVIEW

**Comment by simaob** [comment]
ping @agnessa

**Comment by agnessa** [comment]
let me rebase this to double check, I was under the impression this had been merged 😕

**Comment by aabdaab** [comment]
note that the changes are on staging branch but not on develop

**Comment by simaob** [comment]
really? :-o how did that happen?

**Comment by agnessa** [comment]
OK, can be removed - only contains changes related to secondbase, which we ended up not using here.

**Pull request closed without merging**
